### ISSUE TITLE
[ENTREGA RECUPERATORIO OBJETOS] Nicole Velasco

### ISSUE THREAD

**Issue by nvelascopinto** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-flmgch#1]
Juan Fernandes @juanFdS

**Comment by JuanFdS** [comment]
## Parte A
### Punto 1
⚠️ Podría haber una abstracción para el "número de letras en el nombre del mago", que se usa en un par de lados.
Fuera de ese pequeño detalle, muy bien ✅
### Punto 2
❌ Al primero restarse puntos de energía al vencido y luego otorgarlos al vencedor, sin usar una variable auxiliar, termina pasando que los puntos perdidos por uno no son los mismos que los ganados por el otro.
⚠️ Se rompe el encapsulamiento al pedir siempre la categoría del mago. Sería más independiente de la implementación si el mago en sí entendiese `esVencido` y `puntosPerdidos`, y se pasase luego a sí mismo como parámetro a la categoría. Es decir, en lugar de:
```wollok
        if(magoEnemigo.categoria().esVencido(self, magoEnemigo)) {
            magoEnemigo.disminuirEnergiaMagica(magoEnemigo.categoria().puntosPerdidos(magoEnemigo))
            self.aumentarEnergiaMagica(magoEnemigo.categoria().puntosPerdidos(magoEnemigo))
        }
```
...algo más similar a lo siguiente, delegando en el mago enemigo:
```wollok
        if(magoEnemigo.esVencido(self)) {
            puntosTransferidos = magoEnemigo.puntosPerdidos()
            magoEnemigo.disminuirEnergiaMagica(puntosTransferidos)
            self.aumentarEnergiaMagica(puntosTransferidos)
        }
```
⚠️ No es necesario el método `cambiarCategoria` dado que `categoria` es una `var property`, ya expone un método setter.
Más allá de esto, bien resuelto ✅
## Parte B
### Punto 1
✅
### Punto 2
⚠️ Vuelve a aplicar lo que mencioné en el punto A.2. sobre la rotura del encapsulamiento.
❌ No se implementa que un mago individual pueda desafiar a un gremio (lo cual aparece en los bullet points).
Esta implementación no va a permitir hacer el punto 3 correctamente, pero es adecuada para este punto ✅ 
### Punto 3
❌ El objetivo es que los magos y gremios sean polimórficos entre sí, dado que los mensajes necesarios para que se desafíen entre sí son los mismos (ver si es vencido por otro, ver cuántos puntos pierde, etc.). Dado que está implementado como mensajes separados, debería replantearse la implementación tanto del mago como del gremio.
## Tests
Hay tests para la mayoría de puntos, pero no son exhaustivos (por ejemplo, no se testean todos los objetos mágicos, tampoco el caso en el que un mago o gremio no vence a quien desafía). Además, la discrepancia de puntos perdidos y ganados mencionada en el punto A.2. debería haber sido encontrada por el test del mismo. No suman puntaje adicional.

Nota: 6
